args = commandArgs(trailingOnly=TRUE)

bn<-read.table(args[1], sep=" ", header=F)
wrr<-read.table(args[2], sep=" ", header=F)

pdf(args[3])
min1 <- min(bn$V4)
min2 <- min(wrr$V4)
max1 <- max(bn$V4)
max2 <- max(wrr$V4)
plot(bn$V1, bn$V4, xlab="Number of paths, M", ylab="Average thoughput", type="b", col="dark blue", pch=2, lwd=3, ylim=c(min(c(min1, min2)), max(c(max1, max2))))
points(wrr$V1, wrr$V4, type="b", col="dark red", pch=5, lwd=3)
legend("bottomright", c("BN", "WRR"), pch=c(2,5), lty=c(1,1), inset=c(0,1), xpd=TRUE, horiz=TRUE, bty="n", col=c("dark blue", "dark red"), lwd=3)
grid()
dev.off()
